let P=[],cat="전체",st="all",page=1,per=18,SETTINGS={categories:[],statuses:[],kakaoUrl:"https://open.kakao.com/o/sFesMABh",newDays:3};
let F=new Set(JSON.parse(localStorage.getItem("dangniFavs")||"[]"));
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money=n=>Math.round(Number(n||0)).toLocaleString("ko-KR")+"원";
const crops=["🥕","🥔","🌽","🍠","🍅","🍆","🎃","🧅","🧄","🫛","🫑","🥬"];
function cols(){let w=innerWidth;return w<=640?2:w<=900?4:w<=1200?5:6}
function setPer(){per=cols()*(innerWidth<=640?6:3)}
function cropFor(p){let s=String(p.id||p.name||"작물"),h=0;for(let c of s)h=(h*31+c.charCodeAt(0))>>>0;return crops[h%crops.length]}
function statusText(s){let x=SETTINGS.statuses.find(x=>x.value===s);return x?x.label:({selling:"판매중",soldout:"판매완료",unavailable:"미판매"}[s]||s)}
function dr(p){let v=p.discount??p.discountRate??p.discount_rate??0;if(typeof v==="string")v=v.replace("%","");return Math.max(0,Math.min(100,Number(v)||0))}
function sale(p){return Math.round(Number(p.price||0)*(1-dr(p)/100))}
function price(p){return dr(p)?`<div class="price-row"><span class="discount">${dr(p)}%</span><span class="old-price">${money(p.price)}</span><span class="sale-price">${money(sale(p))}</span></div>`:`<div class="product-price">${money(p.price)}</div>`}
function isNew(p){let raw=p.date||p.registeredAt||p.registered_at;if(!raw)return false;let d=new Date(String(raw).replace(/\./g,"-")+"T00:00:00");if(isNaN(d))return false;let n=new Date();n.setHours(0,0,0,0);let diff=Math.floor((n-d)/86400000);return diff>=0&&diff<3}
function badges(p){return `<div class="badge-stack">${isNew(p)?'<span class="auto-badge new">NEW</span>':''}${dr(p)?`<span class="auto-badge sale">${dr(p)}%</span>`:''}</div>`}
function media(p){let c=cropFor(p);return p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="crop-fallback" style="display:none">${c}</span>`:`<span class="crop-fallback">${c}</span>`}
function filtered(){let q=$("#searchInput").value.trim().toLowerCase();return P.filter(p=>(!q||(p.name+" "+(p.tags||[]).join(" ")).toLowerCase().includes(q))&&(cat==="전체"||p.category===cat)&&(st==="all"||p.status===st))}
function saveFav(){localStorage.setItem("dangniFavs",JSON.stringify([...F]));$("#favoriteCount").textContent=F.size}
function toggle(id){F.has(id)?F.delete(id):F.add(id);saveFav();render()}
function render(){let a=filtered(),pages=Math.max(1,Math.ceil(a.length/per));page=Math.min(page,pages);$("#resultCount").textContent=a.length.toLocaleString();let list=a.slice((page-1)*per,page*per);$("#emptyState").classList.toggle("hidden",!!list.length);$("#products").innerHTML=list.map(p=>`<article class="product-card" data-id="${esc(p.id)}">${badges(p)}<button class="heart ${F.has(p.id)?"faved":""}" data-f="${esc(p.id)}">${F.has(p.id)?"♥":"♡"}</button><div class="product-image">${media(p)}</div><div class="product-info"><span class="status-badge ${p.status}">${statusText(p.status)}</span><div class="product-name">${esc(p.name)}</div>${price(p)}<div class="tags">${(p.tags||[]).slice(0,3).map(t=>`<span class="tag">#${esc(t)}</span>`).join("")}</div></div></article>`).join("");
document.querySelectorAll("[data-f]").forEach(b=>b.onclick=e=>{e.stopPropagation();toggle(b.dataset.f)});document.querySelectorAll(".product-card").forEach(c=>c.onclick=e=>{if(!e.target.closest("[data-f]"))openDetail(c.dataset.id)});
let s=Math.max(1,page-2),e=Math.min(pages,s+4);s=Math.max(1,e-4);$("#pagination").innerHTML=(page>1?`<button data-p="${page-1}">‹</button>`:"")+Array.from({length:e-s+1},(_,i)=>s+i).map(n=>`<button class="${n===page?"on":""}" data-p="${n}">${n}</button>`).join("")+(page<pages?`<button data-p="${page+1}">›</button>`:"");document.querySelectorAll("#pagination button").forEach(b=>b.onclick=()=>{page=+b.dataset.p;render();scrollTo({top:document.querySelector(".shop-toolbar").offsetTop-90,behavior:"smooth"})})}
function openDetail(id){let p=P.find(x=>x.id===id);if(!p)return;$("#modalImage").innerHTML=media(p);$("#modalName").textContent=p.name;$("#modalStatus").className="status-badge "+p.status;$("#modalStatus").textContent=statusText(p.status);$("#modalPrice").innerHTML=price(p);$("#modalTags").innerHTML=(p.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join("");$("#modalId").textContent=p.id||"";$("#modalCategory").textContent=p.category||"";$("#modalDate").textContent=p.date||"";$("#modalBadges").innerHTML=badges(p);$("#modalContact").href=p.kakao||SETTINGS.kakaoUrl;let fav=()=>{$("#modalFavorite").textContent=F.has(id)?"♥ 찜 해제":"♡ 찜하기"};fav();$("#modalFavorite").onclick=()=>{toggle(id);fav()};$("#productModal").classList.remove("hidden");document.body.style.overflow="hidden"}
function showFav(){let a=P.filter(p=>F.has(p.id));$("#favoriteList").innerHTML=a.length?a.map(p=>`<div class="favorite-row"><div class="thumb">${media(p)}</div><div><b>${esc(p.name)}</b><small>${esc(p.category)}</small></div><button data-r="${esc(p.id)}">♥</button></div>`).join(""):`<div class="empty-state"><div>🧺</div></div>`;document.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{toggle(b.dataset.r);showFav()});$("#favoritePanel").classList.remove("hidden");document.body.style.overflow="hidden"}
async function inquire(){let names=P.filter(p=>F.has(p.id)).map(p=>p.name).filter(Boolean),h=$("#copyHint");if(!names.length){h.textContent="바구니에 담긴 작물이 없어요 🌱";return}let t=names.join("\n");try{await navigator.clipboard.writeText(t)}catch(e){let x=document.createElement("textarea");x.value=t;document.body.appendChild(x);x.select();document.execCommand("copy");x.remove()}h.textContent=`${names.length}개 아이템명이 복사됐어요!`;setTimeout(()=>location.href=SETTINGS.kakaoUrl,350)}
$("#searchInput").oninput=()=>{page=1;render()};$("#clearSearch").onclick=()=>{$("#searchInput").value="";page=1;render()};$("#statusFilter").onchange=e=>{st=e.target.value;page=1;render()};$("#favoritesBtn").onclick=showFav;$("#basketInquiry").onclick=inquire;
document.querySelectorAll("[data-close-modal]").forEach(x=>x.onclick=()=>{$("#productModal").classList.add("hidden");document.body.style.overflow=""});document.querySelectorAll("[data-fav-close]").forEach(x=>x.onclick=()=>{$("#favoritePanel").classList.add("hidden");document.body.style.overflow=""});
Promise.all([fetch("settings.json?"+Date.now()).then(r=>r.ok?r.json():SETTINGS).catch(()=>SETTINGS),fetch("products.json?"+Date.now()).then(r=>r.json())]).then(([cfg,a])=>{SETTINGS={...SETTINGS,...cfg};P=a.map(p=>({...p,status:p.status==="reserved"?"unavailable":p.status,images:Array.isArray(p.images)?p.images:[],tags:Array.isArray(p.tags)?p.tags:[]}));let cats=["전체",...SETTINGS.categories];$("#categories").innerHTML=cats.map(c=>`<button class="${c==="전체"?"active":""}" data-c="${esc(c)}">${esc(c)}</button>`).join("");document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{cat=b.dataset.c;page=1;document.querySelectorAll("[data-c]").forEach(x=>x.classList.toggle("active",x===b));render()});$("#statusFilter").innerHTML=`<option value="all">전체 상태</option>`+SETTINGS.statuses.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join("");saveFav();setPer();render()});
let rt;addEventListener("resize",()=>{clearTimeout(rt);rt=setTimeout(()=>{let old=per;setPer();if(old!==per){page=1;render()}},120)});
